name: integration
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build
        run: go build -v -race .
